### PR TITLE
Added Cranmera to the list of MPC frameworks

### PR DESCRIPTION
**Pull request by niekbouman**

### CODE REVIEW

**Comment by rdragos** [comment]
Hi Niek,

Thanks for adding this. Do you have a link with the open source implementation of Cranmera? I would rather have that as is provided with all the other frameworks in the list.

**Comment by niekbouman** [comment]
Hi Dragos,

Currently, the framework is proprietary / not open source...
(perhaps we will license it under AGPL at some point, but this is not clear yet)

best,
Niek

**Comment by rdragos** [comment]
In that case perhaps it's just better to have it listed on the https://www.mpcalliance.org/ website?
The list that is currently on Github is limited to open source software for now.

**Comment by niekbouman** [comment]
Ah, hadn't realised that... sorry!

**Comment by rdragos** [comment]
No problem! I'll close it and we can reopen the issue once the framework is public.

**Comment by GuutBoy** [comment]
@rdragos maybe you should specify in the CONTRIBUTING or README file that you only list public frameworks (which I think is a reasonable decision).

**Comment by rdragos** [comment]
Good point. I think the README has the following 

> everyone can find open-source software designed for MPC as well as introductory material to this topic.

I'll add a note in the CONTRIBUTING as well.

**Pull request closed without merging**
