### PR TITLE
add crypten and spdz2

### PR DESCRIPTION
**Pull request by carlzhangweiwen**

### CODE REVIEW

**Comment by GuutBoy** [comment]
SPDZ-2 is no longer being developed (i.e., has been replaced by SCALE-MAMBA/MP-SPDZ). But maybe this link should be under *Retired Frameworks*.

**Comment by carlzhangweiwen** [comment]
I have delete spdz-2.

**Comment by rdragos** [comment]
I slightly disagree with inserting a link to Damgard et al. paper (SPDZ) along with Crypten library. Mostly because SPDZ line or protocols works for dishonest majority.

After digging a bit into the Crypten it seems to be designed for the semi-honest case...

**Comment by carlzhangweiwen** [comment]
> I slightly disagree with inserting a link to Damgard et al. paper (SPDZ) along with Crypten library. Mostly because SPDZ line of protocols works for dishonest majority.
> 
> After digging a bit into the Crypten it seems to be designed for the semi-honest case...

I find the paper link on the [document of Crypten](https://crypten.readthedocs.io/en/latest/mpctensor.html).
>For technical details see Damgard et al. 2012 and Beaver 1991 outlining the Beaver protocol used in our implementation.

**Comment by GuutBoy** [comment]
There does not seem to be a publication on CrypTen. Maybe a link to the CrypTen website would be more appropriate (https://crypten.ai/).

**Comment by abdelrahamanaly** [comment]
Hi guys,

If I may, I agree with Dragos. It would seem that this distinction is not
explicit unless you dig super deep on the documentation, and in my humble
perspective, SPDZ's main contribution is its active security. If you guys
decide on keeping crypTen on the list, may I suggest to use this blogspot
instead of the SPDZ paper:

https://ai.facebook.com/blog/crypten-a-new-research-tool-for-secure-machine-learning-with-pytorch/

There, they do a more detailed explanation of what they are doing.

Kr,
Abdel

**Comment by rdragos** [comment]
Summing all the comments here I will accept the PR if we got the following description:

MPC with secret sharing; secure against semi-honest adversary; focused on building PyTorch applications with the link of https://crypten.ai/

**Comment by carlzhangweiwen** [comment]
The discription have been updated.

**Pull request merged**
